# Generated by Django 3.0.8 on 2020-08-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ata_emp_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('variance', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ATA REPORT FOR EMPLOYEE',
                'verbose_name_plural': 'ATA REPORT FOR EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='ata_mngr_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('emp_code', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('ata_variance', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ATA REPORT FOR MANAGER',
                'verbose_name_plural': 'ATA REPORT FOR MANAGER',
            },
        ),
        migrations.CreateModel(
            name='audit_score_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('cop', models.IntegerField()),
                ('com', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('cp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'MANAGER AUDIT SCORE',
                'verbose_name_plural': 'MANAGER AUDIT SCORE',
            },
        ),
        migrations.CreateModel(
            name='calibration_report_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('report', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Calibrations Report for Employee',
                'verbose_name_plural': 'calibration Report For Employee',
            },
        ),
        migrations.CreateModel(
            name='calibration_report_mngr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('emp_code', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calibrations Report for Manager',
                'verbose_name_plural': 'calibration Report For Manger',
            },
        ),
        migrations.CreateModel(
            name='CSAT_RR_score',
            fields=[
                ('agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('team_leader', models.CharField(max_length=30)),
                ('csat_score', models.IntegerField()),
                ('rr_score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CSAT RR SCORE',
                'verbose_name_plural': 'CSAT RR SCORE',
            },
        ),
        migrations.CreateModel(
            name='LOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob_name', models.CharField(max_length=30, verbose_name='LOB')),
            ],
        ),
        migrations.CreateModel(
            name='PCD_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default=True, null=True)),
                ('team_leader', models.CharField(max_length=30)),
                ('am', models.IntegerField()),
                ('pcd', models.IntegerField()),
                ('compss', models.IntegerField()),
                ('compo', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('date_time', models.DateTimeField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'PCD SCORE',
                'verbose_name_plural': 'PCD SCORE',
            },
        ),
        migrations.CreateModel(
            name='supervisor_audit_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('cop', models.IntegerField()),
                ('com', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('cp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'SUPERVISOR AUDIT SCORE',
                'verbose_name_plural': 'SUPERVISOR AUDIT SCORE',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='ID')),
                ('mname', models.CharField(max_length=30, verbose_name='Manager name')),
                ('mphone', models.CharField(max_length=30, verbose_name='Manager Phone Number')),
                ('memail', models.EmailField(max_length=254, verbose_name='Manager Email Id')),
                ('mpass', models.CharField(max_length=30)),
                ('elob_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='techerp.LOB', verbose_name='LOB')),
            ],
            options={
                'db_table': 'Manager',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='Employee Id')),
                ('ename', models.CharField(max_length=30, verbose_name='Employee Name')),
                ('ephone', models.CharField(max_length=30, verbose_name='Employee Phone')),
                ('eemail', models.EmailField(max_length=254, verbose_name='Employee Email Id')),
                ('epass', models.CharField(max_length=30)),
                ('lob_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='techerp.LOB', verbose_name='LOB')),
            ],
            options={
                'db_table': 'Employee',
                'managed': True,
            },
        ),
    ]
